"""Investigation models: Lead, Evidence, InvestigationStep, Finding, Exposure, Case.

Mirrors domain/schemas/ for the investigation layer and implements the frozen
forensic contracts specified in the product architecture.
"""
from __future__ import annotations

from enum import Enum
from typing import Any
from pydantic import Field

from .base import CanonicalModel


class Outcome(str, Enum):
    """Forensic finding and case outcome commitments."""
    SUPPORTED = "SUPPORTED"
    REJECTED = "REJECTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class LeadStatus(str, Enum):
    OPEN = "OPEN"
    FOLLOWED = "FOLLOWED"
    DISCARDED = "DISCARDED"


class EvidenceType(str, Enum):
    TRANSACTION = "TRANSACTION"
    INVOICE = "INVOICE"
    REGULATORY_STATUS = "REGULATORY_STATUS"
    RELATIONSHIP = "RELATIONSHIP"
    DOCUMENT = "DOCUMENT"


class EvidenceStrength(str, Enum):
    DIRECT = "DIRECT"
    CORROBORATING = "CORROBORATING"
    CIRCUMSTANTIAL = "CIRCUMSTANTIAL"


class StepDecision(str, Enum):
    FOLLOW = "FOLLOW"
    DISCARD = "DISCARD"
    ESCALATE = "ESCALATE"
    CONCLUDE = "CONCLUDE"


class Signal(CanonicalModel):
    """Raw output from a deterministic detector."""
    signal_id: str
    detector_id: str
    entity_id: str
    severity: str
    details: dict[str, Any] = Field(default_factory=dict)
    detected_at: str | None = None


class Lead(CanonicalModel):
    """A candidate for investigation generated by deterministic detection."""
    lead_id: str
    entity_id: str
    detector_id: str
    reason: str
    risk_score: float = Field(ge=0.0, le=1.0)
    signals: list[str] = Field(default_factory=list)
    status: LeadStatus = LeadStatus.OPEN
    discard_reason: str | None = None


class Evidence(CanonicalModel):
    """A single, sourced, falsifiable claim gathered during investigation."""
    evidence_id: str
    type: EvidenceType
    source_type: str
    source_id: str
    claim: str
    strength: EvidenceStrength
    gathered_by_step_id: str | None = None
    record_hash: str | None = None


class InvestigationStep(CanonicalModel):
    """One bounded tool action taken by the investigator with rationale."""
    step_id: str
    lead_id: str
    action: str
    tool: str
    reason: str
    inputs: dict[str, Any] = Field(default_factory=dict)
    result_refs: list[str] = Field(default_factory=list)
    decision: StepDecision = StepDecision.FOLLOW
    next_action: str | None = None


class Hypothesis(CanonicalModel):
    """Working hypothesis for an investigation thread."""
    thread_id: str
    entity_id: str
    statement: str
    status: str = "TESTING"
    created_at: str | None = None


class Finding(CanonicalModel):
    """Auditable forensic finding evaluated against evidence."""
    finding_id: str
    lead_id: str
    outcome: Outcome
    statement: str
    evidence_ids: list[str] = Field(default_factory=list)
    rationale: str


class Exposure(CanonicalModel):
    """Calculated financial exposure avoiding edge double-counting."""
    root_flow_id: str
    root_amount: float
    downstream_flow: float
    verified_returned_amount: float
    supported_exposure: float
    net_exposure: float
    policy_applied: str


class Case(CanonicalModel):
    """The final auditable case file."""
    case_id: str
    status: str = "SUBSTANTIATED"
    hypothesis: str
    providers_involved: list[str] = Field(default_factory=list)
    amount_involved: float = 0.0
    supporting_evidence: list[str] = Field(default_factory=list)
    discarded_leads: list[dict[str, str]] = Field(default_factory=list)
    confidence_level: str = "HIGH"
    limitations: list[str] = Field(default_factory=list)
    citations: list[str] = Field(default_factory=list)
    generated_at: str | None = None
    evidence_hash: str | None = None
